mobilestoreshop/urls.py
from django.contrib import admin
from django.urls import path, include
from phones import views, models

# used by "tastypie" to do the api
movie_resource = models.MobileResource()

urlpatterns = [
    path('admin/', admin.site.urls),
    path("phones/", include("phones.urls")),
    path("", views.index),
    path("api/", include(movie_resource.urls))
]

phones/urls.py
from django.urls import path
from . import views

app_name = "phones"
urlpatterns = [
    path('registermobile/', views.mobileregistery_form, name='register_mobile'),
    path('registerbrand/', views.brandregistery_form, name='register_brand'),
    path('registermanufacturer/', views.anufacturerregistery_form,name='register_anufacturer'),
    path('updaterecord/', views.update_record, name='update_record'),
    path('reports/', views.report, name='report')
]

phones/models.py
from django.db import models


# implementing models based on the logical model provided on "/logical_model.pdf"

class Manufacturer(models.Model):
    country_name = models.CharField(max_length=50, primary_key=True)

    def __str__(self):
        return self.country_name


class Brand(models.Model):
    name = models.CharField(max_length=50, primary_key=True)
    nationality = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Mobiles(models.Model):
    model_name = models.CharField(max_length=50, primary_key=True)
    color = models.CharField(max_length=50)
    price = models.PositiveIntegerField()
    screen_size = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField()
    manufacturer = models.ForeignKey(
        "Manufacturer", on_delete=models.DO_NOTHING)
    brand = models.ForeignKey("Brand", on_delete=models.CASCADE)

    def __str__(self):
        return self.model_name


# MobileResource Model implemented to provide "api"
from tastypie.resources import ModelResource

class MobileResource(ModelResource):
    class Meta:
        queryset = Mobiles.objects.all()
        resource_name = "Mobiles"

phones/forms.py
from django import forms
from .models import Mobiles, Manufacturer, Brand

# model form for register Mobile
class MobileForm(forms.ModelForm):
    class Meta:
        model = Mobiles
        fields = [i.name for i in Mobiles._meta.get_fields()]
        labels = {"model_name": "مدل گوشی", "color": "رنگ",
                  "price": "قیمت", "screen_size": "سایز صفحه نمایش",
                  "in_stock": "وضعیت", "manufacturer": "کشور سازنده", "brand": "نام برند"}

# model form for register Brand
class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ["name", "nationality"]
        labels = {"name": "نام برند", "nationality": "ملیت برند"}

# model form for register Manufacturer
class ManufacturerForm(forms.ModelForm):
    class Meta:
        model = Manufacturer
        fields = ["country_name"]
        labels = {"country_name": "کشور سازنده"}

# form for filtering records
class BrandNatReportForm(forms.Form):
    choices = [(i.nationality, i.nationality) for i in Brand.objects.all()]
    brand_nationality = forms.ChoiceField(label=" ملیت برند ", choices=choices, required=True)

#  form for filtering records 
class BrandMobReportForm(forms.Form):
    choices = [(i.name, i.name) for i in Brand.objects.all()]
    brand_name = forms.ChoiceField(label="نام برند ", choices=choices, required=True)

#  form for filtering records
class NatManForm(forms.Form):
    nat_choices = [(i.nationality, i.nationality) for i in Brand.objects.all()]
    brand_nationality = forms.ChoiceField(label=" ملیت برند ", choices=nat_choices, required=True)
    man_choices = [(i.country_name , i.country_name ) for i in Manufacturer.objects.all()]
    manufacturer = forms.ChoiceField(label=" کشور سازنده ", choices=man_choices, required=True)

phones/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.utils import timezone
from .forms import MobileForm, BrandForm, ManufacturerForm
from .models import Brand, Manufacturer, Mobiles


def index(request):
    return render(request, "templates/index.html")


# mobile registery form
def mobileregistery_form(request):
    mobile_form = MobileForm()
    if request.method == "GET":
        return render(request, "templates/phones/register_mobile.html", {"mobile_form": mobile_form})
    else:
        f_mobile_form = MobileForm(request.POST)
        model_names = [i.model_name.lower() for i in Mobiles.objects.all()]
        # check the existance of the model_name with no case sensitivity
        if f_mobile_form.is_valid() and request.POST["model_name"].lower() not in model_names:
            f_mobile_form.save()
            return redirect(f"/phones/registermobile/")
        else:
            massage = "این گوشی قبلا ثبت شده است"
            return render(request, "templates/phones/register_mobile.html", {"mobile_form": mobile_form, "massage": massage})


# barnd registery form
def brandregistery_form(request):
    brand_form = BrandForm()
    brand_names = [i.name.lower() for i in Brand.objects.all()]
    if request.method == "GET":
        return render(request, "templates/phones/register_brand.html", {"brand_form": brand_form})
    else:
        f_brand_form = BrandForm(request.POST)
        # check the validity case insensitivitivly
        if f_brand_form.is_valid() and request.POST["name"].lower() not in brand_names:
            f_brand_form.save()
            return redirect("/phones/registermobile/")
        else:
            massage = "این برند قبلا ثبت شده است"
            return render(request, "templates/phones/register_brand.html", {"brand_form": brand_form, "massage": massage})


# manufacturer registery form
def anufacturerregistery_form(request):
    manufacturer_form = ManufacturerForm()
    country_names = [i.country_name.lower()
                     for i in Manufacturer.objects.all()]
    if request.method == "GET":
        return render(request, "templates/phones/register_manufacturer.html",
                      {"manufacturer_form": manufacturer_form})
    else:
        f_manufacturer_form = ManufacturerForm(request.POST)
        # check the validity case insensitivitivly
        if f_manufacturer_form.is_valid() and request.POST["country_name"].lower() not in country_names:
            f_manufacturer_form.save()
            return redirect("/phones/registerbrand/")
        else:
            massage = "این سازنده قبلا ثبت شده است"
            return render(request, "templates/phones/register_manufacturer.html",
                          {"manufacturer_form": manufacturer_form,  "massage": massage})


# updating form
def update_record(request):
    if request.method == "GET":
        status = "search"
        return render(request, "templates/phones/update_record.html", {"status": status})
    # if the request is in getting mobile info for update stage
    elif "model_name_update" in request.POST:
        status = "update"
        filled_form = ""
        massage = ""
        # try if the model_name entered for updating even exist
        try:
            get_object_or_404(Mobiles, pk=request.POST["model_name_update"])
            updating_obj = Mobiles.objects.filter(
                model_name=request.POST["model_name_update"])
            # provide the initial value for updating form
            initial = {"model_name": updating_obj[0].model_name, "color": updating_obj[0].color,
                       "price": updating_obj[0].price, "screen_size": updating_obj[0].screen_size,
                       "in_stock": updating_obj[0].in_stock, "manufacturer": updating_obj[0].manufacturer,
                       "brand": updating_obj[0].brand}
            filled_form = MobileForm(initial=initial)
        except:
            massage = "این گوشی ثبت نشده است"
        return render(request, "templates/phones/update_record.html",
                      {"status": status, "filled_form": filled_form, "massage": massage})
    # check if the request is in submition for perform update stage
    else:
        status = ""
        try:
            updating_obj = get_object_or_404(
                Mobiles, pk=request.POST["model_name"])
            updated_form = MobileForm(request.POST, instance=updating_obj)
            if updated_form.is_valid():
                updated_form.save()
                return redirect("/")
            else:
                massage = "موارد وارد شده معتبر نمی باشد"
        # if the user attempeted to change the model_name
        except:
            massage = "مدل گوشی قابل تغییر نمی باشد"
        return render(request, "templates/phones/update_record.html",
                      {"status": status, "massage": massage})


# for return the Json response
from django.http import JsonResponse
from django.core import serializers
# implemented updating forms
from .forms import BrandNatReportForm, BrandMobReportForm, NatManForm
# get report form
def report(request):
    if request.method == "GET":
        brand_nat_form = BrandNatReportForm()
        brand_mob_form = BrandMobReportForm()
        nat_man_form = NatManForm()
        form = {"brand_nat_form": brand_nat_form,
                "brand_mob_form": brand_mob_form, "nat_man_form": nat_man_form}
        return render(request, "templates/phones/reports.html", form)
    else:
        # filter based on brand nationality
        if 'brand_nationality' in request.POST and 'manufacturer' not in request.POST:
            brand_nationality = request.POST['brand_nationality']
            obj = Brand.objects.filter(nationality=brand_nationality)
            obj_json = serializers.serialize("json", obj)
            data = {"Brands": obj_json}
            return JsonResponse(data)
        # filter based on brand name
        elif 'brand_name' in request.POST:
            brand_names = request.POST["brand_name"]
            obj = Mobiles.objects.filter(brand=brand_names)
            obj_json = serializers.serialize("json", obj)
            data = {"Mobiles": obj_json}
            return JsonResponse(data)
        # filter based on brand nationality and manufacturer natioanily
        elif 'brand_nationality' and 'manufacturer' in request.POST:
            brand_nationality = request.POST["brand_nationality"]
            manufacturer = request.POST["manufacturer"]
            obj = Mobiles.objects.filter(
                brand__nationality=brand_nationality, manufacturer=manufacturer)
            obj_json = serializers.serialize("json", obj)
            data = {"Mobiles": obj_json}
            return JsonResponse(data)
        # filter based on equivalency of brand nationality and manufacturer natioanily
        elif "get_native" in request.POST:
            sql_query = "SELECT model_name, color, in_stock, brand_id, manufacturer_id, screen_size, \
                nationality as brand_nationality FROM (SELECT * FROM phones_mobiles LEFT JOIN phones_brand on \
                    phones_mobiles.brand_id = phones_brand.name) WHERE nationality = manufacturer_id"
            obj = Mobiles.objects.raw(sql_query)
            obj_json = serializers.serialize("json", obj)
            data = {"Mobiles": obj_json}
            return JsonResponse(data)

templates/phones/register_brand.html
<h1>ثبت برند جدید</h1>
{% if massage %}
<h2>{{ massage }}</h2>
{% endif %}
<form action="{% url 'phones:register_brand' %}" method="post">
  {% csrf_token %}
  <br /><br />
  {{ brand_form.as_p }}
  <input type="submit" value="save" />
</form>

templates/phones/register_manufacturer.html
<h1>ثبت کشور سازنده جدید</h1>
{% if massage %}
<h2>{{ massage }}</h2>
{% endif %}
<form action="{% url 'phones:register_anufacturer' %}" method="post">
  {% csrf_token %} {{ manufacturer_form.as_p }}
  <input type="submit" value="save" />
</form>

templates/phones/register_mobile.html
<h1>ثبت گوشی جدید</h1>
<h2>
  اگر برند یا کشور سازنده در لیست انتخابی نیست،ابتدا آنها را با کلید مربوطه ثیت
  کنید
</h2>
{% if massage %}
<h3>{{ massage }}</h3>
{% endif %}
<form action="{% url 'phones:register_mobile' %}" method="post">
  {% csrf_token %}
  {{ mobile_form.as_p }}
  <input type="submit" value=" ثبت " />
</form>

<a href="{% url 'phones:register_anufacturer' %}">
  <button>ثبت کشور سازنده جدید</button>
</a>
<br />
<a href="{% url 'phones:register_brand' %}">
  <button>ثبت برند جدید</button>
</a>

templates/phones/reports.html
<h1>گزارش گیری</h1>
<br />
<form action="{% url 'phones:report' %}" method="post">
  {% csrf_token %} {{ brand_nat_form }}
  <input type="submit" value=" مشاهده برند های این ملیت " />
</form>
<br />
<p>-----------------------------------------------------------------</p>
<br />
<form action="{% url 'phones:report' %}" method="post">
  {% csrf_token %} {{ brand_mob_form }}
  <input type="submit" value=" مشاهده لیست موبایل تحت این برند " />
</form>
<br />
<p>-----------------------------------------------------------------</p>
<br />
<form action="{% url 'phones:report' %}" method="post">
  {% csrf_token %} {{ nat_man_form.as_p }}
  <input type="submit" value=" فیلتر لیست موبایل ها " />
</form>
<br />
<p>-----------------------------------------------------------------</p>
<br />
<form action="{% url 'phones:report' %}" method="post">
  {% csrf_token %}
  <label for="native"> گوشی های دارای ملیت برند و تولید کننده یکسان </label>
  <input type="radio" name="get_native" id="native" checked />
  <input type="submit" value=" اعمال " />
</form>
<br />
<p>-----------------------------------------------------------------</p>
<br />
<button><a href="/api/Mobiles"> هدایت به اند پوینت </a></button>

templates/phones/update_record.html
<h1>به روز رسانی گوشی ثبت شده</h1>
<h2>{{ massage }}</h2>
<form action="{% url 'phones:update_record' %}" method="post">
  {% csrf_token %}
  {% if status == "search" %}
    <label for="model_name"> مدل گوشی را وارد کنید </label>
    <input type="text" name="model_name_update" id="model_name" />
    <input type="submit" value=" جست و جو " />
  {% elif status == "update" %}
    {% if filled_form %}
        {{ filled_form.as_p}}
    <input type="submit" value=" ذخیره تغییرات " />
    {% endif %}
    <br/><br/>
    <a href="{% url 'phones:register_anufacturer' %}">
      <button>ثبت کشور سازنده جدید</button>
    </a>
    <a href="{% url 'phones:register_brand' %}">
      <button>ثبت برند جدید</button>
    </a>
  {% endif %}
</form>